### ISSUE TITLE
suggest

### ISSUE THREAD

**Issue by ironme** [corwin42/AHActionBar#1]
Can you add more events to your AHSwipetoRefresh (B4A LIBRARY)? When AHSwipetoRefresh's father container rolls to the bottom. I'm sorry to ask the question in your AHActionBar because I didn't find your AHSwipetoRefresh project.

**Comment by corwin42** [comment]
I guess AHSwipetoRefresh is not available on Github.

Please send feature requests to the B4X forum: https://www.b4x.com/android/forum/
